### ISSUE TITLE
Unittesting with the Native C++ framework in Visual Studio

### ISSUE THREAD

**Issue by Strooom** [deftio/travis-ci-cpp-example#4]
Hi Manu,

I read your tutorial and it's really helpful, but now I want to do unit testing with the **built-in native c++ framework in Visual Studio**.
I do have testfiles that run fine locally, but I don't know how to have them run on Travis. I have a Travis account and automatic builds is working already. Now I'd like to add unit tests. Could you help me with that ? In return I will document the proces so you can add it to your examples in this repo.
thanks. Pascal

**Comment by deftio** [comment]
Do you have a .travis.yml file and have you enabled your repo on travis-ci?

**Comment by Strooom** [comment]
Yes, simply building works fine (see my repo 'logging').
But now I want to extend to unit-testing, and preferably the Visual Studio native C++ test.
I think it is possible to have Travis set up a Windows machine, with Visual Studio 2017.
Then I think VS allows to run the tests from the command line...
So all that together is what I'd like to get working. But Travis CI is very new to me, so I'm looking for other people who may have solved this before.

**Comment by deftio** [comment]
OK.  I looked at your file in /logging  (main branch).   

Some thoughts here:
I don't see where your test code is in the repo.  Perhaps the repo is a commit behind your local.  In any case you should be able to drive your tests from command line (gtest / boost etc) and pass that result of that test to travis-ci.  This is how the Cpp example I made works.  However I don't have any mocks for Arduino in the repo.   


I found this example repo (https://github.com/Arduino-CI/Blink) and  look at .travis.yml and  the /tests/ directory and the /scripts/ directory.   This looks similar to what you have checked in.

The tricky part about that is the use of ruby and mocks to drive all the testing in the cloud.  I haven't used the Arduino-CI but the explanations given in the /Blink repo seem pretty good for a starter.


-Manu

BTW - cool to see another guy hacking on microcontrollers - I've spent a lot of time on them too.

**Comment by Strooom** [comment]
Thanks,

I am using the Arduino-CI example, it works great. The Ruby part comes included in Travis and worked out of the box.
The Unit Testing I want is similar to gtest / boost but a different framework : the built-in framework for Visual Studio. It runs unit tests for all the code which is hardware INdependent. The big advantage is that you can use the debugger on these tests, ie . you can step through the code, see the callstack, variable values etc..

So I guess the next step is get Visual Studio running in Travis CI, then run the tests from the commandline. I'll keep you posted.

**Comment by Strooom** [comment]
Other option is to move to gtest, it seems to be more popular and more supported...

**Comment by deftio** [comment]
I think gtest (like you mentioned) will be easier to run in Travis-CI than VSStudio.  LMK how it goes
